version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: test_database2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MochiMochi99
      POSTGRES_DB: CandidateApplication
    volumes:
      - "/Users/adalatadiljan/Documents/Docker/postgres/data"
      - "/Users/adalatadiljan/Documents/Docker/postgres/init-scripts:/docker-entrypoint-initdb.d"
    ports:
      - "5430:5432"
    restart: always