# Use an official OpenJDK image as a base
##FROM openjdk:17-jdk

# Set the working directory inside the container
##WORKDIR /app

# Copy the built JAR file into the container
##COPY target/api-gateway.jar api-gateway.jar

# Expose the API Gateway's port
##EXPOSE 8081

# Command to run the application
##ENTRYPOINT ["java", "-jar", "api-gateway.jar"]

